# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Sync

on:
  schedule:
    # Run @ 12:00 UTC every Thursday
    - cron: '0 12 * * 4'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: google
      - uses: actions/checkout@v4
        with:
          repository: DefinitelyTyped/DefinitelyTyped
          token: ${{ secrets.PUBTAGS_BOT_REPO_TOKEN }}
          path: dt
          ref: master
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Run dprint
        working-directory: ./google
        run: |
          cp ../dt/.dprint.jsonc .
          npx --yes dprint fmt -- '*.ts'
      - name: Run sync script
        id: sync
        run: python google/.github/workflows/sync.py
        shell: sh
        continue-on-error: true
      - name: Verify DefinitelyTyped compliance
        if: steps.sync.outcome == 'success'
        id: verify
        working-directory: ./dt
        run: |
          pnpm install -w --filter "{./types/google-publisher-tag}..."
          pnpm test google-publisher-tag
      - name: Create Pull Request
        if: steps.verify.outcome == 'success'
        uses: peter-evans/create-pull-request@v3
        with:
          path: dt
          push-to-fork: publisher-ads-audits-bot/DefinitelyTyped
          token: ${{ secrets.PUBTAGS_BOT_REPO_TOKEN }}
          title: "Sync latest changes to @types/google-publisher-tag"
          body: "Automated PR to update @types/google-publisher-tag"
          commit-message: "Sync latest changes to @types/google-publisher-tag"
          branch: "sync/google-publisher-tag"
          delete-branch: true
