# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: google
          ref: ${{ github.head_ref }}
      - uses: actions/checkout@v4
        with:
          repository: DefinitelyTyped/DefinitelyTyped
          token: ${{ secrets.PUBTAGS_BOT_REPO_TOKEN }}
          path: dt
          ref: master
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Run linter
        working-directory: ./google
        run: |
          npm run test
      - name: Run dprint
        working-directory: ./google
        run: |
          cp ../dt/.dprint.jsonc .
          npx --yes dprint fmt -- '*.ts'
      - name: Run sync script
        id: sync
        run: python google/.github/workflows/sync.py
        shell: sh
        continue-on-error: true
      - name: Verify DefinitelyTyped compliance
        if: steps.sync.outcome == 'success'
        id: verify
        working-directory: ./dt
        run: |
          pnpm install -w --filter "{./types/google-publisher-tag}..."
          pnpm test google-publisher-tag
